CREATE DATABASE IF NOT EXISTS druid DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'druid'@'%' IDENTIFIED BY 'password';
ALTER USER 'druid'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT ALL PRIVILEGES ON druid.* TO 'druid'@'%';
FLUSH PRIVILEGES;
