CREATE DATABASE IF NOT EXISTS druid DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'druid'@'%' IDENTIFIED BY 'IndIan@123';
ALTER USER 'druid'@'%' IDENTIFIED WITH mysql_native_password BY 'IndIan@123';
GRANT ALL PRIVILEGES ON druid.* TO 'druid'@'%';
FLUSH PRIVILEGES;
